[package]
name = "MessagingServer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
reqwest ="0.11"
tokio = { version = "1", features = ["full"] }
ctrlc = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
urlencoding = "1"
clearscreen = "4"
